on: [push]
jobs:
  build:
    name: Trigger
    runs-on: ubuntu-latest
    steps:
    - name: trigger Jenkins pipeline job
      uses: appleboy/jenkins-action@master
      with:
        url: "https://jenkins.sdpmlab.org/"
        user: "SuperGavinHsu"
        token: ${{11620e4600fabe12e7b8bb47e52ba7ea87}}
        job: "410977019"
