on: [push]
jobs:
  build:
    name: Trigger
    runs-on: ubuntu-latest
    steps:
    - name: trigger Jenkins pipeline job
      uses: appleboy/jenkins-action@master
      with:
        url: "https://jenkins.sdpmlab.org/"
        user: "410977019"
        token: ${{secrets.TOKEN}}
        job: "410977019"
